### ISSUE TITLE
Double generator produces the values that repeat too often

### ISSUE THREAD

**Issue by vmandrychenko** [GarnerCorp/test-charged#6]
I noticed that Generate.double.value is producing values that repeat pretty often. This results in a lot of flaky tests. I also have a feeling there is the same problem with Ints and strings. We fetch by random value and get the data unexpectedly (not so random after all). Take a look at distribution:

0.0
10654.40514007162
-25000.0
9809.305301695917
-17137.603961595465
-13373.27128064092
-17173.188179482015
16215.946247337735
25000.0
-1.0
2589.5009772317026
2989.3820258243213
-1.0
1.0
14621.637434678836
6639.72649885136
4480.467924157816
15071.979639947393
-7803.325196510235
0.0
-13639.018501387918
-1.0
0.0
-1.0
25000.0
0.0
-680.0489962394313
25000.0
0.0
5603.971067112001
1.0
25000.0
-3492.0292956218727
1914.9050728849652
1.0
22126.890952288304
1.0
6454.447629369719
15965.27860647165
6313.167878111624
18430.9741005084
-22972.349963552137
-11222.655123316128
-25000.0
8014.81489075796
2307.609420652556
-25000.0
18074.95636105605
-7175.513714450248
0.0
1218.9087878974278
-25000.0
0.0
16849.186106839807
-7690.1377231373845
-7782.421061686346
0.0
-3344.0802255245944
1.0
0.0
-25000.0
4893.948251260506
8270.36394507093
-25000.0
25000.0
-7114.822557374027
4289.880108282228
0.0
2206.825253589799
0.0
1.0
1.0
-24578.837875688303
1.0
6921.482685096758
24474.803752991596
-20810.114858273846
25000.0
-20079.297251322576
12549.678213572632
21720.167108810077
1.0
-1.0
-12238.999581847349
-17554.682615207123
24373.376291099776
-25000.0
21716.763270486073
13288.834895604676
0.0
-15452.159393295105
-25000.0
-25000.0
1.0
1.0
7592.477246329603
-12954.522292076497
-8686.495748247775
-1.0
-17837.222289273202
25000.0
25000.0
-25000.0
-13569.92578868068
-1.0

**Comment by fulrich** [comment]
Quickly looking into this it looks like this is the expectation of `chooseNum` in ScalaCheck. 

```scala
/** Generates numbers within the given inclusive range, with
   *  extra weight on zero, +/- unity, both extremities, and any special
   *  numbers provided. The special numbers must lie within the given range,
   *  otherwise they won't be included. */
  def chooseNum[T](minT: T, maxT: T, specials: T*)(
```

I'm guessing this it to put an emphasis on edge cases which certainly makes sense when using the properties directly in a test. When used for our use case of faking and generating test data it certainly feels odd. I think if we swap out these calls in `SignGenerator` it should fix the issue.

Now I wonder the best way to create a test that checks that we are getting a sufficient spread of values.
